import type { Page } from "../shared/types";
import { embed } from "./embeddings";
import { processWithGemini } from "./gemini";

export interface ProcessedPageFields {
  summary?: string;
  embedding: number[];
  tags: string[];
}

// Embeddings stay on-device (MiniLM, for semantic search — never leaves the
// browser). Summary/tags are generated by Gemini via the backend proxy
// (ai/gemini.ts) — that call needs the backend running locally with
// GEMINI_API_KEY set in backend/.env.
export async function processPage(page: Page): Promise<ProcessedPageFields> {
  const text = `${page.title}\n\n${page.content}`;
  const [embedding, gemini] = await Promise.all([
    embed(text),
    processWithGemini(page.title, page.content),
  ]);
  return { summary: gemini.summary, embedding, tags: gemini.tags };
}
